version: '3'

services:
  # goapp:
  #   build: .
  #   volumes:
  #     - .:/go/app
  #   platform: linux/amd64
  #   ports:
  #     - "8000:8000"
  #   extra_hosts:
  #     - "host.docker.internal:172.17.0.1"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
      MYSQL_PASSWORD: root
    networks:
      - backend
    # extra_hosts:
    #   - "host.docker.internal:172.17.0.1"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - backend

networks:
  backend:
    name: backend
