POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Product",
    "price": 100,
    "category": "Category",
    "sub_category": "Subcategory",
    "offer_percertage": null,
    "quantity": 89
}

###

GET http://localhost:8000/products
Content-Type: application/json